// Code generated by "stringer -type Animal"; DO NOT EDIT.

package gogenerate

import "strconv"

//func _() {
//	// An "invalid array index" compiler error signifies that the constant values have changed.
//	// Re-run the stringer command to generate them again.
//	var x [1]struct{}
//	_ = x[Dog-0]
//	_ = x[Pig-1]
//	_ = x[Cat-2]
//	_ = x[Tiger-3]
//	_ = x[Lion-4]
//}

const _Animal_name = "DogPigCatTigerLion"

var _Animal_index = [...]uint8{0, 3, 6, 9, 14, 18}

func (i Animal) String() string {
	if i < 0 || i >= Animal(len(_Animal_index)-1) {
		return "Animal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Animal_name[_Animal_index[i]:_Animal_index[i+1]]
}
